# Generated by Django 3.2.7 on 2021-11-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "vehicle_id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("brand", models.CharField(max_length=60, verbose_name="Brand")),
                ("model", models.CharField(max_length=60, verbose_name="Model")),
                ("horse_power", models.IntegerField(verbose_name="Horse Power")),
                (
                    "build_year",
                    models.DateField(auto_now_add=True, verbose_name="Date"),
                ),
                (
                    "euro_category",
                    models.IntegerField(
                        choices=[
                            (1, "LOW"),
                            (2, "SEMI-LOW"),
                            (3, "MEDIUM"),
                            (4, "SENIOR"),
                            (5, "MODERATE"),
                        ],
                        default=1,
                        verbose_name="Euro Category",
                    ),
                ),
            ],
        ),
    ]
