# Generated by Django 3.2.7 on 2021-11-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Price'),
        ),
    ]
