version: "3"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    image: app:django
    container_name: django_container
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: dealership
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Radina.987
    container_name: postgres_db
