version: "3"

services:
  web:
    container_name: django_container
    build: .
    command: >
      sh -c "python manage.py migrate && gunicorn app.wsgi ./gunicorn.conf.py"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    container_name: postgres_container
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_NAME: ${POSTGRES_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    restart: always

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"

  swagger:
    container_name: swagger-ui
    image: swaggerapi/swagger-ui
    volumes:
      - ./swagger.yml:/swagger.yml
    environment:
      SWAGGER_JSON: /swagger.yml
    ports:
      - "${SWAGGER_UI_PORT}:8080"
