# Generated by Django 3.2.7 on 2021-11-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trucks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=60, verbose_name='Brand')),
                ('model', models.CharField(max_length=60, verbose_name='Model')),
                ('horse_power', models.IntegerField(verbose_name='Horse Power')),
                ('build_year', models.DateField(verbose_name='Date')),
                ('max_load', models.IntegerField(choices=[(1, 1000), (2, 2000), (3, 3000), (4, 4000), (5, 5000), (5, 6000)], default=1, verbose_name='Euro Category')),
                ('price', models.IntegerField(default=0, verbose_name='Price')),
            ],
        ),
    ]
