# Generated by Django 3.2.9 on 2021-11-29 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=60, verbose_name='Brand')),
                ('model', models.CharField(max_length=60, verbose_name='Model')),
                ('horse_power', models.IntegerField(verbose_name='Horse Power')),
                ('build_year', models.DateField(verbose_name='Date')),
                ('vehicle_type', models.CharField(choices=[(1, 'NEW'), (2, 'USED'), (3, 'SCRAP')], default=2, max_length=10, verbose_name='Vehicle Type')),
                ('location', models.CharField(blank=True, max_length=60, null=True, verbose_name='Location')),
                ('price', models.IntegerField(default=0, verbose_name='Price')),
                ('euro_category', models.CharField(choices=[(1, 'LOW'), (2, 'SEMI-LOW'), (3, 'MEDIUM'), (4, 'SENIOR'), (5, 'MODERATE')], default=1, max_length=10, verbose_name='Euro Category')),
            ],
            options={
                'ordering': ['price'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trucks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=60, verbose_name='Brand')),
                ('model', models.CharField(max_length=60, verbose_name='Model')),
                ('horse_power', models.IntegerField(verbose_name='Horse Power')),
                ('build_year', models.DateField(verbose_name='Date')),
                ('vehicle_type', models.CharField(choices=[(1, 'NEW'), (2, 'USED'), (3, 'SCRAP')], default=2, max_length=10, verbose_name='Vehicle Type')),
                ('location', models.CharField(blank=True, max_length=60, null=True, verbose_name='Location')),
                ('price', models.IntegerField(default=0, verbose_name='Price')),
                ('max_load', models.IntegerField(choices=[(1, 1000), (2, 2000), (3, 3000), (4, 4000), (5, 5000), (5, 6000)], default=1, verbose_name='Euro Category')),
            ],
            options={
                'ordering': ['price'],
                'abstract': False,
            },
        ),
    ]
