# Generated by Django 3.2.7 on 2021-11-22 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
        ('trucks', '0001_initial'),
        ('dealership', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealership',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars.cars'),
        ),
        migrations.AlterField(
            model_name='dealership',
            name='trucks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trucks', to='trucks.trucks'),
        ),
    ]
