# Generated by Django 3.2.7 on 2021-11-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealership',
            name='location',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Location'),
        ),
    ]
