# Generated by Django 3.2.7 on 2021-11-22 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealership', '0002_auto_20211122_0904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealership',
            old_name='trucks',
            new_name='truck',
        ),
    ]
